### ISSUE TITLE
Auto sticker not working 

### ISSUE THREAD

**Issue by bilalking99** [prabathLK/PRABATH-MD#44]
Hi dear
Auto customize sticker are not working in new update.. please fix this

**Comment by prabathLK** [comment]
> Hi dear Auto customize sticker are not working in new update.. please fix this

No, it  work.

 See if you have set auto sticker - customize in settings.

 Check if the url of the image is correct.

 Also, the auto sticker does not work with the bot number, that is, if you send a message from that number, it will not reply to the same number.  Test by sending a message to someone else.

**Comment by bilalking99** [comment]
All and everything is ok...
Still not working

**Comment by prabathLK** [comment]
> All and everything is ok... Still not working
contact us - 94762280384
